baseURL = 'https://www.christopherjones.us/'
languageCode = 'en-us'
title = 'Chris W Jones'
theme = 'papermod'

[params.homeInfoParams]
Title = "Chris W Jones"
Content = "Hobbiest Programmer"

[[params.socialIcons]]
name = "Dustbuster Club"
url = "https://dustbuster.club/@odo"

[[params.socialIcons]]
name = "GitHub"
url = "https://www.github.com/magikid"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "digitalocean"
URL = "s3://cwj-website?endpoint=nyc3.digitaloceanspaces.com&region=US"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true
